### ISSUE TITLE
Packaging license file

### ISSUE THREAD

**Issue by jakirkham** [erdogant/pypickle#1]
It would be great to have the license file included in packages like wheels and source distributions.

To do this would recommend adding `license_files=["LICENSE"],` to [the `setup` function in `setup.py`]( https://github.com/erdogant/pypickle/blob/f3df97268a2064930b0bdcc04730c632f04cd244/setup.py#L15 ). From there [setuptools should handle the rest]( https://setuptools.pypa.io/en/latest/userguide/declarative_config.html?highlight=license_files#metadata ).

**Comment by erdogant** [comment]
I released it already!
